"""empty message

Revision ID: b3ae7dfbd09f
Revises: 2a9c24fb1ecb
Create Date: 2021-09-09 11:52:20.651910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ae7dfbd09f'
down_revision = '2a9c24fb1ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=True)
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
